appname: "UrlDancer"
layout: "main"
charset: "UTF-8"
template: "template_toolkit"
time_zone: "Europe/Amsterdam"

logger: "console"
log: "core"
show_errors: 1

engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'

plugins:
  DBIC:
    default:
      schema_class: "UrlDancer::Schema"
      dsn: "dbi:SQLite:dbname=data/urldancer.db"

plack_middlewares:
  -
    - Plack::Middleware::ReverseProxy
